name: golden_screenshot
description: Utilities to automate screenshot generation using Flutter's golden tests.
version: 0.0.1
repository: https://github.com/adil192/golden_screenshot

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/topbars/
